pipeline {

    agent any
    
    stages {
        stage('Build docker image') {
            steps {
                sh 'echo "Building Docker image......"'
                script {
                 dockerapp = docker.build("moglesonlima/lab-jenkins:${env.BUILD_ID}", '-f ./dir/Dockerfile ./dir')
                }
            }
        }

        stage('Push docker image') {
            steps {
                sh 'echo "Pushing Docker image to registry..."'
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'echo "Deploying to Kubernetes cluster...."'
            }
        }  
    }
        
}
